# Autogenerated wrapper script for OCamlbuild_jll for x86_64-linux-musl
export ocamlbuild

JLLWrappers.@generate_wrapper_header("OCamlbuild")
JLLWrappers.@declare_executable_product(ocamlbuild)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        ocamlbuild,
        "bin/ocamlbuild",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
